OPEN-ENT-NG/wiki

.github/pull_request_template.md

Adding pull_request_template.md in .github directory

chore(template): add PR template and .github folder

---

src/main/resources/public/ts/behaviours.ts

Passing from 5 last updated wiki pages to 15 displayed on the left side menu of wiki current page
Create a wiki topic / Click on the topic / create or modify 16 relative pages for this topic / only 15 will be displayed on last updated pages on the left side.
[CO-1686](https://jira.support-ent.fr/browse/CO-1686)

feat(pagination): #CO-1686 set last pages from 5 to 15

---

build.sh

Adding code in build.sh to check whether dist-tags exists before npm install on entcore. Before, local branch name was directly used to launch npm install on entcore@localbranch resulting crash because this tag doesn't exist on entcore repository.
Create local branch with random name on wiki. Try buildNode before changes, it should crash. Try after changes, it should work.
[CO-1720](https://jira.support-ent.fr/browse/CO-1720)

chore(build): #CO-1720 prevent buildNode from crashing

---

.github/workflows/dev-check-repository.yml

Implementation of CI and unit tests for wiki module.
[CO-1719](https://jira.support-ent.fr/browse/CO-1719)

chore(github): adding CI workflow github action

---

backend/src/main/java/net/atos/entng/wiki/controllers/WikiController.java
backend/src/main/java/net/atos/entng/wiki/service/WikiService.java
backend/src/main/java/net/atos/entng/wiki/service/WikiServiceMongoImpl.java

notify EUR in service for wiki update and delete

feat: #WB2-1763, notify EUR in service for wiki update/delete

---

frontend/src/features/wiki/NewPage.tsx
frontend/src/routes/wiki/index.tsx

Ajout du bouton "Nouvelle page" dans la side bar a gauche. 
Ticket : https://edifice-community.atlassian.net/browse/WB2-1515

feat: #WB2-1515, add button to create page and redirect

---

frontend/pnpm-lock.yaml
frontend/src/routes/wiki/index.tsx
frontend/src/store/index.ts
frontend/src/store/treeview/index.ts

Ajout du composant TreeView dans la side bar à gauche en récupérant les pages composant le wiki. 
Ticket : https://edifice-community.atlassian.net/browse/WB2-1513
PR associé : https://github.com/edificeio/edifice-ui/pull/215

feat: #WB2-1513, add treeview component in side bar with content

---

backend/src/main/java/net/atos/entng/wiki/controllers/WikiController.java
backend/src/main/java/net/atos/entng/wiki/service/WikiService.java
backend/src/main/java/net/atos/entng/wiki/service/WikiServiceMongoImpl.java
frontend/src/mocks/index.ts
frontend/src/models/page.ts
frontend/src/services/api/__tests__/index.spec.ts
frontend/src/services/api/index.ts
frontend/src/services/queries/__tests__/index.spec.tsx
frontend/src/services/queries/page.ts
frontend/src/services/queries/wiki.ts

Clean APIs URL and Responses according to the wiki migration.

feat: #WB2-1763, clean APIs

---

backend/src/main/java/net/atos/entng/wiki/controllers/WikiController.java

Normalize rights and create explorer share service

feat: #WB2-1754, normalize rights

---

backend/src/main/java/net/atos/entng/wiki/Wiki.java
backend/src/main/java/net/atos/entng/wiki/controllers/WikiController.java
backend/src/main/java/net/atos/entng/wiki/service/WikiService.java
backend/src/main/java/net/atos/entng/wiki/service/WikiServiceMongoImpl.java

Add Tiptap Transformer to related page content APIs:
- getPage (GET /wiki/:wikiId/page/:pageId)
- createPage (POST /wiki/:idwiki/page)
- updatePage (PUT /wiki/:wikiId/page/:pageId)
No need to keep old content like in Blog.

feat: #WB2-1755, add Tiptap Transformer to page content

---

backend/src/main/java/net/atos/entng/wiki/controllers/WikiController.java
backend/src/main/java/net/atos/entng/wiki/service/WikiService.java
backend/src/main/java/net/atos/entng/wiki/service/WikiServiceMongoImpl.java

- Get children pages for a page in `GET /wiki/:id` API
- Add parentId field in a page in `POST /wiki/:id/page/:pageId` API
- Update parentId field in a page in `PUT /wiki/:id/page/:pageId` API

feat: #WB2-1769, handle Parent/Children pages

---

backend/src/main/resources/i18n/fr.json
frontend/src/features/wiki/ContentHeader.test.tsx
frontend/src/features/wiki/ContentHeader.tsx
frontend/src/routes/page/index.tsx
frontend/src/routes/wiki/index.tsx

- Ajout du bouton d'édition d'une page. 
- Ajout des tests pour savoir si les selon les droits utilisateur le bouton d'édition doit être affiché ou non. 
- Petites modifications / clean code
Ticket : https://edifice-community.atlassian.net/browse/WB2-1597

feat: #WB2-1597, add edit button + add test on user rights

---

backend/src/main/java/net/atos/entng/wiki/controllers/WikiController.java
backend/src/main/java/net/atos/entng/wiki/service/WikiService.java
backend/src/main/java/net/atos/entng/wiki/service/WikiServiceMongoImpl.java
backend/src/main/resources/jsonschema/page.json
frontend/src/features/page/FormPage/index.tsx
frontend/src/hooks/useFeedData.ts
frontend/src/hooks/useFilterVisiblePage.ts
frontend/src/models/page.ts
frontend/src/models/payload.ts
frontend/src/routes/page/create.tsx
frontend/src/routes/page/edit.tsx
frontend/src/routes/page/list.tsx

Handle isVisible status in page creation and edition:
- backend APIs for handling isVisible status in page creation/edition APIs
- frontend to handle isVisible toggle in page creation/edition form

feat: #WB2-1593, handle isVisible status in page creation and edition

---

frontend/src/features/app/AppActions.tsx
frontend/src/features/wiki/ContentHeader.tsx
frontend/src/store/wiki/index.ts

- Add check to show or hide `history` action in page dropdown
- Add logic to handle show/hide history modal in wiki store.
- Clean use of rights

feat: #WB2-1581, add history action in dropdown and modal actions

---

backend/src/main/resources/i18n/fr.json
frontend/src/features/page/PageHeader/PageHeader.tsx

Affichage du badge de visibilité sur la page de consultation d'une page

feat: #WB2-1531, add visibility badge in page read display

---

backend/src/main/java/net/atos/entng/wiki/controllers/WikiController.java
backend/src/main/java/net/atos/entng/wiki/service/WikiService.java
backend/src/main/java/net/atos/entng/wiki/service/WikiServiceMongoImpl.java

Rename add page comment route from `@Post("/:id/page/:idpage")` to `@Post("/:id/page/:idpage/comment")` and refactor some code like handlers to arrow functions...

refactor: #WB2-1870, refactor add comment route

---

backend/gradle.properties
backend/src/main/java/net/atos/entng/wiki/controllers/WikiController.java
backend/src/main/java/net/atos/entng/wiki/service/WikiService.java
backend/src/main/java/net/atos/entng/wiki/service/WikiServiceMongoImpl.java
frontend/src/services/api/index.ts

Add update comment API.
Also adapt frontend API call.

feat: #WB2-1871, add "update comment" API

---

backend/src/main/java/net/atos/entng/wiki/controllers/WikiController.java
backend/src/main/java/net/atos/entng/wiki/service/WikiSearchingEvents.java
frontend/src/routes/root/index.tsx

- Change old route in backend controllers
- Add redirect to old route `#view/...` to redirect wiki and pages when notified
All tests passed
https://edifice-community.atlassian.net/browse/WB2-1834

feat: #WB2-1834, change redirection wiki and pages with new frontend routes

---

backend/src/main/java/net/atos/entng/wiki/service/WikiServiceMongoImpl.java
frontend/src/routes/page/edit.tsx

When switching parent page visibility => update subpages visibility accordingly

feat: #WB2-1582, add visibility update for subPages in backend API

---

backend/deployment/wiki/migration/2.0.0/addPagePosition.js
backend/src/main/java/net/atos/entng/wiki/service/WikiServiceMongoImpl.java
backend/src/main/resources/jsonschema/page.json

Ce commit ajoute le champ position dans le process de mis à jour et dans le json schema
Il contient un script pour migrer tout les anciens wiki pour leur ajouter un champs position

feat: wb21890, ajout des positions sur les pages et migration

---

frontend/src/routes/page/create.tsx

Fix the visibility issue when creating a page.

fix: #WB2-1897, fix visibility bug on page creation

---

backend/deployment/wiki/migration/2.0.0/addNewRights.js
backend/src/main/java/net/atos/entng/wiki/controllers/WikiController.java
backend/src/main/java/net/atos/entng/wiki/service/WikiService.java
backend/src/main/java/net/atos/entng/wiki/service/WikiServiceMongoImpl.java
backend/src/main/resources/i18n/fr.json
frontend/package.json
frontend/src/features/page/RevisionHeader/RevisionHeader.test.tsx
frontend/src/features/page/RevisionHeader/RevisionHeader.tsx
frontend/src/features/page/RevisionModal/RevisionModal.test.tsx
frontend/src/features/page/RevisionModal/RevisionModal.tsx
frontend/src/hooks/useCheckablePrint.ts
frontend/src/hooks/useRevision.test.tsx
frontend/src/hooks/useRevision.ts
frontend/src/mocks/index.ts
frontend/src/mocks/node.ts
frontend/src/mocks/setup.vitest.tsx
frontend/src/routes/errors/not-found.tsx
frontend/src/routes/index.tsx
frontend/src/routes/page/edit.tsx
frontend/src/routes/page/index.tsx
frontend/src/services/api/index.test.ts
frontend/src/services/api/index.ts
frontend/src/services/queries/page/page.test.tsx
frontend/src/services/queries/page/page.ts
frontend/src/services/queries/wiki/wiki.test.tsx

Ce commit embarque la consultation d'une ancienne version pour une page ainsi que la possibilité de restaurer cette ancienne version. 
- [X ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ X] I have commented my code, particularly in hard-to-understand areas
- [ X] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ X] If it is a consequent feature, I have added thorough tests.
- [X ] I have added tests that prove my fix is effective or that my feature works
- [ X] Any dependent changes have been added to this project (must specify in **Description**)

feat: #WB2-1529, add revision page and actions

---

backend/src/main/java/net/atos/entng/wiki/service/WikiServiceMongoImpl.java
frontend/src/features/page/RevisionModal/RevisionModal.test.tsx
frontend/src/features/page/RevisionModal/RevisionModal.tsx
frontend/src/features/page/RevisionModal/useRevisionModal.ts
frontend/src/hooks/useRevision.ts

Cette évo ajoute l'action de restauration dans la vue "historique des versions"

feat: #WB2-1528, restore version from history

---

frontend/src/hooks/useFormPage.test.ts
frontend/src/hooks/useFormPage.tsx
frontend/src/mocks/index.ts
frontend/src/utils/findPage.test.ts
frontend/src/utils/findPage.ts

Corrige le soucis de toggle de visibilité disabled lors de la création ou modification d'une sous page d'une page parent visible.

fix: #WB2-1915, fix subPage visibility toggle

---

backend/src/main/resources/i18n/fr.json
frontend/src/features/index.ts
frontend/src/features/page/DeleteListModal/DeleteListModal.tsx
frontend/src/features/page/DeletePageModal/DeletePageModal.tsx
frontend/src/features/page/RevisionModal/RevisionModal.test.tsx
frontend/src/features/page/RevisionModal/RevisionModal.tsx
frontend/src/hooks/index.ts
frontend/src/routes/index.tsx
frontend/src/routes/page/index.tsx
frontend/src/routes/page/list.tsx
frontend/vite.config.ts

- Add a new component `List` with the necessary props
- Show "List pages"
- Clean files import
https://edifice-community.atlassian.net/browse/WB2-1535

feat: #WB2-1535, add List component to show list of pages

---

backend/src/main/java/net/atos/entng/wiki/service/WikiServiceMongoImpl.java
frontend/src/hooks/useFeedData.ts
frontend/src/models/page.ts
frontend/src/routes/page/index.tsx

In treeview and page view, we check if user has rights to see a page, depending on user rights and page visibility.

fix: #WB2-1894, check if user has rights to see a page

---

frontend/src/config/explorer.ts
frontend/vite.config.ts

fix: #WB2-1823, add Duplicate action

---

backend/deployment/wiki/migration/2.0.0/addNewRights.js
backend/src/main/java/net/atos/entng/wiki/controllers/WikiController.java
backend/src/main/java/net/atos/entng/wiki/service/WikiService.java
backend/src/main/java/net/atos/entng/wiki/service/WikiServiceMongoImpl.java
backend/src/main/java/net/atos/entng/wiki/to/PageListEntryFlat.java
backend/src/main/java/net/atos/entng/wiki/to/PageListEntryTree.java
backend/src/main/java/net/atos/entng/wiki/to/PageListRequest.java
backend/src/main/java/net/atos/entng/wiki/to/PageListResponse.java
backend/src/main/resources/jsonschema/pageUpdateList.json

Ce commit ajoute la possibilité de modifier les pages en lot (position et parent)
Il reçoit une liste à plat et retourne une arborescence

feat: #WB2-1521, bulk update pages

---

backend/src/main/resources/i18n/fr.json
frontend/src/features/page/FormPage/FormPage.tsx

Add disabled toggle tooltip : https://edifice-community.atlassian.net/browse/WB2-1892

fix: #WB2-1892, add disabled toggle tooltip

---

backend/deployment/wiki/migration/2.0.0/addNewRights.js
backend/src/main/java/net/atos/entng/wiki/controllers/WikiController.java
backend/src/main/java/net/atos/entng/wiki/service/WikiService.java
backend/src/main/java/net/atos/entng/wiki/service/WikiServiceMongoImpl.java
backend/src/main/resources/jsonschema/pageDeleteList.json
backend/src/test/java/net/atos/entng/wiki/service/WikiServiceMongoImplTest.java

Ce commit ajoute la possibilité de supprimer des pages en lots

feat: #WB2-1918, bulk delete pages

---

backend/src/main/java/net/atos/entng/wiki/controllers/WikiController.java

Do not notify hidden page creation and hidden page comment creation.
I've edited `notify` method in backend Controller to check in case of a hidden page creation do not send notification and in case of hidden page comment creation do not send notification neither.

feat: #WB2-1914, do not notify hidden page creation and hidden page comment creation

---

backend/src/main/java/net/atos/entng/wiki/controllers/WikiController.java
backend/src/main/java/net/atos/entng/wiki/service/WikiServiceMongoImpl.java

Ce fix déporte le check des droits sur les pages dans le service car il n'est pas possible de lire le body de la requête plus d'une fois

feat: #WB2-1918, check bulk delete page inside service

---

backend/src/main/java/net/atos/entng/wiki/controllers/WikiController.java
backend/src/main/java/net/atos/entng/wiki/service/WikiService.java
backend/src/main/java/net/atos/entng/wiki/service/WikiServiceMongoImpl.java
backend/src/main/resources/i18n/fr.json
frontend/pnpm-lock.yaml
frontend/src/mocks/index.ts
frontend/src/models/page.ts
frontend/src/routes/index.tsx
frontend/src/routes/old-format/index.tsx
frontend/src/routes/page/index.tsx
frontend/src/services/api/index.ts
frontend/src/services/queries/page/page.ts

Ce fix permet d'afficher les anciens contenus html

feat: #WB2-1878, add old content view

---

backend/src/main/java/net/atos/entng/wiki/controllers/WikiController.java
backend/src/main/java/net/atos/entng/wiki/service/WikiService.java
backend/src/main/java/net/atos/entng/wiki/service/WikiServiceMongoImpl.java
backend/src/main/resources/i18n/timeline/fr.json
backend/src/main/resources/view/notify/page-deleted.html
backend/src/main/resources/view/notify/page-deleted.json

For pages deletion API, we check if user is different from page author to send page author deletion notification.

feat: #WB2-1845, send page author delete notification

---

frontend/src/routes/wiki/index.tsx

Hide subpage creation button in tree for readonly users

fix: #WB2-1997, hide subpage creation button in tree for readonly users

---

frontend/src/features/page/FormPage/FormPage.tsx
frontend/src/hooks/useFormPage/useFormPage.tsx

Only manager can view visibility Toggle in create/edit page form

fix: #WB2-1991, only manager can view visibility Toggle in create/edit page form

---

backend/src/main/java/net/atos/entng/wiki/controllers/WikiController.java
backend/src/main/java/net/atos/entng/wiki/service/WikiServiceMongoImpl.java
backend/src/test/java/net/atos/entng/wiki/service/WikiServiceMongoImplTest.java

Fix: Add comment creation notification for page author.
Refactor page/comment notification methods: page creation and comment creation notification were in the same method with a lot of condition, it wasn't clear to read and complicated to maintain so I split the code in two methods, each specific to use case, I think it will be easier to maintain.

fix: #WB2-1914, fix comment creation notification for page author and refactor page/comment notification methods

---

backend/src/main/resources/i18n/fr.json
frontend/pnpm-lock.yaml
frontend/src/features/page/DuplicateModal/DuplicateModal.test.tsx
frontend/src/features/page/DuplicateModal/DuplicateModal.tsx
frontend/src/features/page/PageHeader/PageHeader.tsx
frontend/src/hooks/useFilteredWikis.ts
frontend/src/mocks/handlers.ts
frontend/src/mocks/index.ts
frontend/src/mocks/setup.ts
frontend/src/models/page.ts
frontend/src/providers/index.tsx
frontend/src/routes/old-format/index.tsx
frontend/src/routes/page/index.tsx
frontend/src/services/api/index.test.ts
frontend/src/services/api/index.ts
frontend/src/services/queries/page/page.test.tsx
frontend/src/services/queries/page/page.ts
frontend/src/services/queries/wiki/wiki.ts
frontend/src/store/wiki/index.ts

Cette feature ajoute la module de duplication

feat: #WB2-1698, add duplicate modal

---

backend/src/main/resources/i18n/fr.json
frontend/src/hooks/useRevision/useRevision.ts
frontend/src/models/page.ts
frontend/src/routes/page/create.tsx
frontend/src/routes/page/edit.tsx
frontend/src/routes/page/index.tsx
frontend/src/routes/wiki/index.tsx
frontend/src/services/queries/comment.ts
frontend/src/store/toast/index.ts
frontend/src/store/wiki/index.ts

Ajout des toasts sur les différentes actions : 
- Enregistrer une page 
- Restauration d’une version
- Duplication
- Suppression
- Création / Suppression / Edition d’un commentaire 
Ticket : https://edifice-community.atlassian.net/browse/WB2-1541

feat: #WB2-1541, add toasts actions create delete edit

---

backend/deployment/wiki/migration/2.0.0/addPageVisibility.js

Add page visibility migration script

fix: #WB2-2005, add page visibility migration script

---

frontend/src/features/page/PrintModal/PrintModal.test.tsx
frontend/src/features/page/PrintModal/PrintModal.tsx
frontend/src/features/page/RevisionModal/RevisionModal.test.tsx
frontend/src/hooks/useCheckablePrint.ts
frontend/src/hooks/useListPage/useListPage.tsx
frontend/src/hooks/useRevision/useRevision.ts
frontend/src/routes/page/list/list.test.tsx
frontend/src/routes/page/list/list.tsx
frontend/src/store/wiki/index.ts

Ce fix branche les actions dans la vue liste

feat: #WB2-1990, link actions in list view

---

backend/src/main/java/net/atos/entng/wiki/controllers/WikiController.java
backend/src/main/resources/i18n/timeline/fr.json
backend/src/main/resources/view/notify/page-updated.html
backend/src/main/resources/view/notify/page-updated.json

Notify users when a page is updated from hidden to visible.
>
>

feat: #WB2-2096, notify page updated to visible

---

backend/src/main/java/net/atos/entng/wiki/service/WikiServiceMongoImpl.java

Update Wiki modified date when updating or creating a page
>
>

fix: #WB2-2104, update Wiki modified date when updating or creating a page

---

frontend/src/features/page/DuplicateModal/DuplicateModal.tsx
frontend/src/features/page/FormPage/FormPage.tsx
frontend/src/features/page/RevisionHeader/RevisionHeader.tsx

Disable submit button when clicked once, for:
- Save page
- Restore page
- Duplicate page
>
>

fix: #WB2-2155, disable submit button when clicked once

---

frontend/src/routes/page/index.tsx

https://edifice-community.atlassian.net/browse/WB2-1882
>
>

feat(comments): WB2-1882, add userRights to CommentProvider to allow manager to delete comment

---

backend/src/main/java/net/atos/entng/wiki/service/WikiServiceMongoImpl.java

Update revision for hidden page
>
>

fix: #WB-2002, update revision for hidden page

---

backend/src/main/java/net/atos/entng/wiki/controllers/WikiController.java

Notify wiki shared manager users if a comment is created by someone else on a page
>
>

fix: #WB2-2126, notify wiki shared manager users if a comment is created by someone else on a page

---

frontend/src/features/page/PageHeader/PageHeader.test.tsx
frontend/src/features/page/PrintModal/PrintModal.test.tsx
frontend/src/features/page/RevisionHeader/RevisionHeader.test.tsx
frontend/src/features/page/RevisionModal/RevisionModal.test.tsx
frontend/src/hooks/useFormPage/useFormPage.test.ts
frontend/src/hooks/useRevision/useRevision.test.ts
frontend/src/mocks/handlers.ts
frontend/src/mocks/index.ts
frontend/src/services/api/index.test.ts
frontend/src/services/queries/page/page.test.tsx
frontend/src/utils/dtoToPage.ts
frontend/src/utils/findPage.test.ts

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
>
>
>

fix: #WB2-2015, set page visiblity to true if field is missing

---

backend/src/main/java/net/atos/entng/wiki/service/WikiServiceMongoImpl.java
frontend/src/models/comment.ts
frontend/src/routes/page/index.tsx
frontend/src/services/api/index.ts
frontend/src/services/queries/comment.ts
frontend/src/utils/dtoToPage.ts

Add comment replies component to Wiki frontend
>
>

feat: #WB2-1941, add Comment replies to frontend

---

backend/pom.xml
backend/src/main/java/net/atos/entng/wiki/Wiki.java
backend/src/main/java/net/atos/entng/wiki/listeners/ResourceBrokerListenerImpl.java

Ce commit ajoute:
- un listener sur le broker pour récupérer les info concernant une ressource
- un listener permettant de partager/départager une ressource dans wiki
>
>
>

feat: #PEDAGO-2699, link into community

---

backend/src/main/java/net/atos/entng/wiki/Wiki.java
backend/src/main/java/net/atos/entng/wiki/explorer/WikiExplorerPlugin.java
backend/src/main/java/net/atos/entng/wiki/service/WikiServiceMongoImpl.java

Ce commit publie les event de suppression de wiki sur le broker
>
>
>

feat: #PEDAGO-3019, notify deleted resources on broker
